version: '3.7'

services:
  db:
    image: mongo:4.0.4
    container_name: mongo_dnd
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dnd_admin
      - MONGO_INITDB_ROOT_PASSWORD=eulalia
      - MONGO_INITDB_DATABASE=dnd_fastapi_dev
    ports:
      - 127.0.0.1:27017-27019:27017-27019
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - backend
  api:
    restart: unless-stopped
    depends_on:
      - db
    build: ./src/api
    volumes:
      - ./src/api:/usr/src/api/
    ports:
      - 8002:8000
    environment:
      - MONGO_URL=mongodb://dnd_admin:eulalia@db:27017/
      - AUTHJWT_SECRET_KEY='superdupersecret'
      - AUTHJWT_ACCESS_TOKEN_EXPIRES=604800
    links:
      - "db:mongo_dnd"
    networks:
      - frontend
      - backend
  webapp:
    restart: unless-stopped
    depends_on:
      - db
      - api
    build: ./src/webapp
    volumes:
      - ./src/webapp:/webapp
    ports:
      - 3000:3000
    environment:
      - API_URL=http://localhost:8002
    networks:
      - frontend

volumes:
  mongo_data:
  mongo_config:

  #appdir:

networks:
  frontend:
  backend:
